
mod 'puppetlabs-inifile', '6.0.0'
mod 'puppetlabs-firewall', '5.0.0'
mod 'puppetlabs-stdlib', '8.6.0'
mod 'puppetlabs-concat', '8.0.0'
mod 'puppet-systemd', '4.2.0'
mod 'puppetlabs-ntp', '10.0.0'
mod 'puppetlabs-apache', '10.0.0'
mod 'theforeman-tftp', '8.0.0'
mod 'theforeman-dhcp', '8.2.0'